ws:
  Protocol: ws
  ip: 192.168.3.14
  port: 3001

http:
  Protocol: http
  ip: 192.168.3.14
  port: 3000

bot:
  master: QQ

plugin:
  xunfei:
    api_url:
    api_key:
    model: generalv3.5
    personality: You are a helpful assistant.