ws:
  Protocol: ws
  ip: 127.0.0.1
  port: 3001

http:
  Protocol: http
  ip: 127.0.0.1
  port: 3000
  sync: true

plugin:
  xunfei:
    api_url:
    api_key:
    model: generalv3.5
    personality: You are a helpful assistant.