name: Publish to PyPI

on:
  push:
    branches:
      - main  # 指定触发的分支，根据实际情况修改
    paths:
      - "ncatbot/__init__.py"  # 只有当 __init__.py 文件发生变化时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 根据你的项目需求调整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies
        run: |
          poetry install

      - name: Build and publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish --build --no-interaction
